// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

// GetValueFromCache provides a mock function with given fields: key
func (_m *RedisClient) GetValueFromCache(key string) (string, error) {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetValueInCache provides a mock function with given fields: key, value, _a2
func (_m *RedisClient) SetValueInCache(key string, value string, _a2 time.Duration) error {
	ret := _m.Called(key, value, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) error); ok {
		r0 = rf(key, value, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
